export const WIZARD_FIELD_INVENTORY = {
  step1: {
    step: 1,
    title: "Know Your Client",
    fields: [
      {
        key: "lookingFor",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "fundingAmount",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "businessLocation",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "industry",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "purposeOfFunds",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "salesHistory",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "revenueLast12Months",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "monthlyRevenue",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "accountsReceivable",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
      {
        key: "fixedAssets",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step1_KYC.tsx",
      },
    ],
  },
  step2: {
    step: 2,
    title: "Product Category Selection",
    fields: [
      {
        key: "selectedProductId",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step2_Product.tsx",
      },
      {
        key: "productCategory",
        source: "form",
        required: false,
        enforcedBy: [],
        file: "Step2_Product.tsx",
      },
      {
        key: "selectedProductType",
        source: "form",
        required: false,
        enforcedBy: [],
        file: "Step2_Product.tsx",
      },
      {
        key: "selectedProduct",
        source: "form",
        required: false,
        enforcedBy: [],
        file: "Step2_Product.tsx",
      },
      {
        key: "requires_closing_cost_funding",
        source: "form",
        required: false,
        conditional:
          "isEquipmentIntent && app.requires_closing_cost_funding === undefined && app.applicationToken && !LinkedApplicationStore.has(app.applicationToken)",
        enforcedBy: ["submit", "ui"],
        file: "Step2_Product.tsx",
      },
    ],
  },
  step3: {
    step: 3,
    title: "Business Information",
    fields: [
      {
        key: "businessName",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "legalName",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "businessStructure",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "address",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "city",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "state",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "zip",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "phone",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "website",
        source: "form",
        required: false,
        enforcedBy: [],
        file: "Step3_Business.tsx",
      },
      {
        key: "startDate",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "employees",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
      {
        key: "estimatedRevenue",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step3_Business.tsx",
      },
    ],
  },
  step4: {
    step: 4,
    title: "Applicant Information",
    fields: [
      {
        key: "firstName",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "lastName",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "email",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "phone",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "street",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "city",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "state",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "zip",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "dob",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "ssn",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "ownership",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "hasMultipleOwners",
        source: "form",
        required: false,
        enforcedBy: [],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.firstName",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.lastName",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.email",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.phone",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.street",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.city",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.state",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.zip",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.dob",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.ssn",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
      {
        key: "partner.ownership",
        source: "form",
        required: true,
        conditional: "values.hasMultipleOwners",
        enforcedBy: ["ui", "submit"],
        file: "Step4_Applicant.tsx",
      },
    ],
  },
  step5: {
    step: 5,
    title: "Required Documents",
    fields: [
      {
        key: "entry.document_type",
        source: "document",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step5_Documents.tsx",
      },
      {
        key: "documentsDeferred",
        source: "store",
        required: false,
        enforcedBy: [],
        file: "Step5_Documents.tsx",
      },
    ],
  },
  step6: {
    step: 6,
    title: "Terms & Typed Signature",
    fields: [
      {
        key: "primary_applicant_id",
        source: "document",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step6_Review.tsx",
      },
      {
        key: "partner_applicant_id",
        source: "document",
        required: false,
        conditional: "hasPartner",
        enforcedBy: ["ui", "submit"],
        file: "Step6_Review.tsx",
      },
      {
        key: "typedSignature",
        source: "signature",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step6_Review.tsx",
      },
      {
        key: "coApplicantSignature",
        source: "signature",
        required: false,
        conditional: "hasPartner",
        enforcedBy: ["ui", "submit"],
        file: "Step6_Review.tsx",
      },
      {
        key: "signatureDate",
        source: "derived",
        required: true,
        enforcedBy: [],
        file: "Step6_Review.tsx",
      },
      {
        key: "termsAccepted",
        source: "form",
        required: true,
        enforcedBy: ["ui", "submit"],
        file: "Step6_Review.tsx",
      },
    ],
  },
} as const;
