export const MockLenderProducts = [
  {
    productId: "loc_1",
    category: "Line of Credit",
    minAmount: 50000,
    maxAmount: 250000,
    supportedCountries: ["CA", "US"],
    requiredDocs: ["bank_statements_6m"],
    businessQuestions: ["businessAddress", "revenue"],
    applicantQuestions: ["firstName", "lastName", "email"],
  },
  {
    productId: "loc_2",
    category: "Line of Credit",
    minAmount: 200000,
    maxAmount: 1000000,
    supportedCountries: ["US"],
    requiredDocs: ["bank_statements_6m"],
    businessQuestions: ["businessAddress", "revenue", "yearsInBusiness"],
    applicantQuestions: ["firstName", "lastName", "email"],
  },
  {
    productId: "fact_1",
    category: "Factoring",
    minAmount: 25000,
    maxAmount: 500000,
    supportedCountries: ["CA"],
    requiredDocs: ["bank_statements_6m", "invoices"],
    businessQuestions: ["businessAddress", "revenue", "invoicesOutstanding"],
    applicantQuestions: ["firstName", "lastName"],
  },
  {
    productId: "term_1",
    category: "Term Loan",
    minAmount: 250000,
    maxAmount: 2000000,
    supportedCountries: ["US"],
    requiredDocs: ["bank_statements_6m"],
    businessQuestions: ["businessAddress", "revenue", "yearsInBusiness"],
    applicantQuestions: ["firstName", "lastName", "email", "dob"],
  },
  {
    productId: "equip_1",
    category: "Equipment Financing",
    minAmount: 50000,
    maxAmount: 750000,
    supportedCountries: ["CA", "US"],
    requiredDocs: ["bank_statements_6m", "equipment_quote"],
    businessQuestions: ["businessAddress", "revenue", "equipmentDetails"],
    applicantQuestions: ["firstName", "lastName", "email"],
  },
  {
    productId: "po_1",
    category: "Purchase Order Financing",
    minAmount: 100000,
    maxAmount: 1500000,
    supportedCountries: ["US"],
    requiredDocs: ["bank_statements_6m", "purchase_orders"],
    businessQuestions: ["businessAddress", "revenue", "purchaseOrders"],
    applicantQuestions: ["firstName", "lastName", "email"],
  },
];

export type LenderProduct = typeof MockLenderProducts[number];
