export interface ApplicationResponse {
  applicationId?: string;
  documents?: unknown[];
  documents_deferred?: unknown[];
  documentsDeferred?: unknown[];
  applicant?: Record<string, any>;
  business?: Record<string, any>;
  product_category?: string;
  productCategory?: string;
  kyc?: Record<string, any>;
  financialProfile?: Record<string, any>;
  selectedProduct?: unknown;
  selected_product?: unknown;
  selectedProductId?: unknown;
  selected_product_id?: unknown;
  selectedProductType?: unknown;
  selected_product_type?: unknown;
  requires_closing_cost_funding?: boolean;
  termsAccepted?: boolean;
  terms_accepted?: boolean;
  typedSignature?: string;
  typed_signature?: string;
  coApplicantSignature?: string;
  co_applicant_signature?: string;
  signatureDate?: string;
  signature_date?: string;
  currentStep?: number;
  current_step?: number;
  linkedApplicationTokens?: unknown;
  linked_application_tokens?: unknown;
  documentReviewComplete?: boolean;
  document_review_complete?: boolean;
  ocrComplete?: boolean;
  ocr_complete?: boolean;
  financialReviewComplete?: boolean;
  financial_review_complete?: boolean;
  creditSummaryComplete?: boolean;
  credit_summary_complete?: boolean;
}
