name: Document Enum Contract Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'client/src/lib/documentCategories.ts'
      - 'shared/documentTypes.ts'
      - 'scripts/validateEnumSnapshot.ts'
      - 'scripts/checkEnumMatch.test.ts'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'client/src/lib/documentCategories.ts'
      - 'shared/documentTypes.ts'
      - 'scripts/validateEnumSnapshot.ts'
      - 'scripts/checkEnumMatch.test.ts'

jobs:
  validate-enum-contract:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate Staff App Enum Snapshot
      run: npx tsx scripts/validateEnumSnapshot.ts
      
    - name: Check Client Document Enum Contract
      run: npx jest scripts/checkEnumMatch.test.ts --verbose
      
    - name: Upload enum snapshot artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: document-type-snapshot
        path: shared/documentTypeSnapshot.json
        
  enum-security-check:
    runs-on: ubuntu-latest
    needs: validate-enum-contract
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Check for enum modifications
      run: |
        # Check if documentCategories.ts was modified
        if git diff --name-only HEAD~1 HEAD | grep -q "client/src/lib/documentCategories.ts"; then
          echo "⚠️ documentCategories.ts was modified"
          echo "Validating changes are authorized..."
          
          # Check commit message for authorization token
          if git log -1 --pretty=%B | grep -q "\[ENUM-AUTHORIZED\]"; then
            echo "✅ Enum modification authorized in commit message"
          else
            echo "❌ Enum modification not authorized"
            echo "Add [ENUM-AUTHORIZED] to commit message to authorize enum changes"
            exit 1
          fi
        else
          echo "✅ No enum modifications detected"
        fi